### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by robin-snt** [dgraph-io/pydgraph#101]
Please create a sphinx generated API definition.

The readme and examples are not sufficient to understand how this client works. It would be extremely helpful if there at least an API overview, where the classes and functions were clearly defined in terms of input and output. E.g: https://2.python-requests.org/en/master/api/#main-interface

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8238). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
