### ISSUE TITLE
How to do conditional upsert with variables?

### ISSUE THREAD

**Issue by robin-snt** [dgraph-io/pydgraph#103]
In #102 I had problems with the upsert in that example, which were resolved when setting `name` as a hard coded string value: `NODE as q(func: eq(name, "foo"))`.

This confirms that what would to me seem as an intuitive way to combine query variables and upsert does not work.

Is it possible to do such an operation and if so, can you perhaps provide documentation for doing this correctly?

**Comment by martinmr** [comment]
You should be able to include the variables declared in the query inside the condition.

See the example in this section of our docs: https://docs.dgraph.io/mutations/#conditional-upsert

**Comment by martinmr** [comment]
@mangalaman93 can you quickly check if my answer is correct? Thanks.

**Comment by robin-snt** [comment]
> EDIT: this works only with variables defined inside the query, not with GraphQL-like variables (e.g $name, etc).

I am referring to the pydgraph client functionality to correctly pass variables to the upsert query as shown in this standard query example: https://github.com/dgraph-io/pydgraph/blob/master/examples/simple/simple.py#L117-L136 -- I want to do the same for upsert queries.

I've not been able to pass python variables into an upsert query and I've had to resort to python string interpolation, which is far from ideal.

**Comment by mangalaman93** [comment]
This is correct. GraphQL variables do not work with upsert currently. There is an issue pending here https://github.com/dgraph-io/dgraph/issues/4286. Let me see if we could get this fixed soon.

**Comment by robin-snt** [comment]
I think this should be stated explicitly in documentation.

**Comment by mangalaman93** [comment]
This would be fixed soon, it is filed as a bug.

**Comment by mangalaman93** [comment]
This is already fixed in dgraph/master. Please let us know if you still face any issues.
