### ISSUE TITLE
Add asynchronous request execution possibility

### ISSUE THREAD

**Issue by sausageRoll** [dgraph-io/pydgraph#112]
I'm looking for something similar to https://github.com/dgraph-io/dgraph4j#using-the-asynchronous-client. Maybe integration with async and tasks. Is that possible?

**Comment by martinmr** [comment]
Looking into this. I haven't worked with python async tools too much but from what I gather most of that support is in python 3. Which might be a problem given that we are still supporting python 2.

**Comment by martinmr** [comment]
So it looks like this is supported by grpc: https://grpc.io/docs/tutorials/basic/python/#calling-service-methods
