### ISSUE TITLE
Missing docs for gRPC deadline setting

### ISSUE THREAD

**Issue by ptsilva** [dgraph-io/pydgraph#118]
How can we set gRPC deadline on pydgraph?
I can't found any docs about. It's mentioned on dgraph docs with shortest path and recurse query.
https://docs.dgraph.io/query-language/#k-shortest-path-queries

**Comment by martinmr** [comment]
Sorry. I will document this. All the client methods have a keyword argument called timeout: You use it like `client.alter(op, timeout=0.5)`. The timeout should be a number representing the timeout in seconds.

I'll keep this open to track adding documentation about this feature.
