### ISSUE TITLE
Connection health check when creating client

### ISSUE THREAD

**Issue by Kryptiique** [dgraph-io/pydgraph#128]
Hey Dgraph folks, I was wondering if there was a way to check if a connection to a Dgraph instance is available immediately after the pydgraph client is setup. This way, I can check before hand if my first queries/mutations are going to fail. I've found the `checkVersion` method and was hoping to use that as an alternative solution, but couldn't figure out how to use it. Specifically, I couldn't figure out what the `check` object is supposed to be, since it isn't well documented. I would rather not have to perform a bogus query on the client instead, as it doesn't seem like the best solution to me.

Thank you.

**Comment by martinmr** [comment]
The check_version should work but it's only in the client stub, not in the client itself. I'll add it to the client so that you can use it. You won't have to pass a check object. That's just an empty object because gRPC doesn't allow calls with no arguments.
