### ISSUE TITLE
Streaming API for DgraphClient.txn().query()

### ISSUE THREAD

**Issue by coderfromhere** [dgraph-io/pydgraph#134]
Hi!

I'd like to know if there's a streaming API to consume results of `DgraphClient.txn().query()` with constant memory regardless of the result set.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8255). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
