### ISSUE TITLE
Adding edge facet is not working

### ISSUE THREAD

**Issue by robin-snt** [dgraph-io/pydgraph#136]
Dgraph: v20.03.1
pydgraph: 20.3.0

First I tried using json format, which didn't work then I tried N-quads which is mutated using the following function:

```python
def set_facet(client, src_uid, trg_uid, predicate, facets):
    '''Set edge facets

    :param client: dgraph client object
    :param src_uid: dgraph source node UID
    :type src_uid: str
    :param trg_uid: dgraph source node UID
    :type trg_uid: str
    :param predicate: dgraph edge predicate
    :type predicate: str
    :param facets: facet key, value tuple
    :type facets: ((str, str|bool|int|float), ...)
    '''

    nquads = '\n'.join(f'<{src_uid}> <{predicate}> <{trg_uid}> '
                       f'({k}={json.dumps(v)}) .' for k, v in facets)

    print('FACET:', nquads)
    txn = client.txn()

    try:
        txn.mutate(set_nquads=nquads, commit_now=True)
    finally:
        txn.discard()
```

I execute my python script and verify that the nquad is logged to stdout:
`FACET: <0x13a4a> <result> <0x13a24> (cached=true) .`

.. and inspect the graph:

![Screenshot from 2020-05-29 16-54-43](https://user-images.githubusercontent.com/53257569/83273940-639fb500-a1cd-11ea-8f47-04f5a4bfcf0f.png)

![Screenshot from 2020-05-29 16-57-55](https://user-images.githubusercontent.com/53257569/83274173-b4afa900-a1cd-11ea-8c48-494ac172845b.png)

No facets to be seen, and I know the function executed. When I copy-paste the n-quad from stdout and execute a mutation query in ratel:
```
{
  set {
    <0x13a4a> <result> <0x13a24> (cached=true) .
  }
}
```

, the graph is mutated:

![Screenshot from 2020-05-29 17-03-01](https://user-images.githubusercontent.com/53257569/83274690-618a2600-a1ce-11ea-9552-ccf0d2e89c0c.png)

**Comment by martinmr** [comment]
I added a test for facet mutation in https://github.com/dgraph-io/pydgraph/pull/146 and I am able to mutate with facets. I tested master as well as the 20.03.1 release.

There are two possible causes for your issue that I can think of:

1. Some issue with rate. I'd recommend using the client or ratel to retrieve the node instead of the graphical interface.
1. Some issue with the encoding of your nquads. To discard this option, I'd suggest testing your code with a hardcoded mutation.

**Comment by robin-snt** [comment]
Thank you for the feedback.

> I added a test for facet mutation in #146 and I am able to mutate with facets.

I would argue that with the current mess that dgraph facets are in right now, there are different ways of handling facets and it seems to me that the test you added doesn't cover all the different cases. However, the difference between the facets in that test and my situation is that I am adding facets to existing nodes, and the test is simply writing a new subgraph containing facets on some edges. I also think there should be a test for dealing with facets for schema type `[uid]`.

>  I'd recommend using the client or ratel to retrieve the node instead of the graphical interface.

Isn't ratel and the GUI the same?

> I'd suggest testing your code with a hardcoded mutation.

I'm not sure this point is valid, because I print the encoded nquad to stdout and successfully run it in ratel.

**Comment by martinmr** [comment]
Sorry, by not using the graphical interface I meant not using the node explorer and instead writing a query to see what you get back in the JSON response.

I'll see what additional cases I can. However, I doubt the issue is in pydgraph itself as the client is just sending the mutations and does not modify the input.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8256). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
