### ISSUE TITLE
Test Requirements/Docs

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/pydgraph#139]
There are some extra requirements needed for running tests.  Suggestion to add `tests/requirements.txt` (below). 
Documentation on testing requirements, 
* docker cli
* go w/ `$GOPATH`
* `dgraph` git repo in `$GOPATH/src/github.com/dgraph-io/`

This is from pip freeze from virtualenv after installing:
* `./requirements.txt`
* `grpcio-tools`
* `coveralls`
* `docker-compose` (needed later needed by `dgraph/contrib/scripts/functions.sh`)

```
attrs==19.3.0
bcrypt==3.1.7
cached-property==1.5.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
coverage==5.1
coveralls==2.0.0
cryptography==2.9.2
docker==4.2.0
docker-compose==1.25.5
dockerpty==0.4.1
docopt==0.6.2
grpcio==1.29.0
grpcio-tools==1.29.0
idna==2.9
jsonschema==3.2.0
paramiko==2.7.1
protobuf==3.12.2
pycparser==2.20
pydgraph==20.3.0
PyNaCl==1.4.0
pyrsistent==0.16.0
PyYAML==5.3.1
requests==2.23.0
six==1.15.0
texttable==1.6.2
urllib3==1.25.9
websocket-client==0.57.0
```

**Comment by martinmr** [comment]
I updated the requirements file in #140 

I also updated the README to include info on the Dgraph requirement and go in #137 

I'll update the readme again to include info on docker.

**Comment by darkn3rd** [comment]
:+1:
