### ISSUE TITLE
Add async examples.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/pydgraph#143]

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8687). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by mangalaman93** [comment]
There are a few examples in the README https://github.com/dgraph-io/pydgraph/pull/199
