### ISSUE TITLE
How to commit transactions as batch?

### ISSUE THREAD

**Issue by heshuguo** [dgraph-io/pydgraph#148]
As titled.

**Comment by anurags92** [comment]
Do you want to load a bunch of data together? You can try [Bulk Loader](https://dgraph.io/docs/deploy/#bulk-loader) for that. Also checkout https://discuss.dgraph.io, much of our community lives there and you can get faster answers.

**Comment by heshuguo** [comment]
Okay. Thanks.

**Comment by heshuguo** [comment]
just checked the doc about bulk loader. it seems not work for my case. 
Here is from doc:
Dgraph Bulk Loader serves a similar purpose to the Dgraph Live Loader, but can only be used to load data into a new cluster. It cannot be run on an existing Dgraph cluster. Dgraph Bulk Loader is considerably faster than the Dgraph Live Loader and is the recommended way to perform the initial import of large datasets into Dgraph.

here is my case:
about 50000 transactions per second to insert to dgraph, is there a good way to make it faster?

**Comment by anurags92** [comment]
I think it should work but 50K txn per second would be stretching the system. From the [benchmarks done in 2017](https://dgraph.io/blog/post/benchmark-neo4j/), we achieved 46.7K txn per second. I do not understand why would bulk loader not work for your use case?

**Comment by heshuguo** [comment]
> I think it should work but 50K txn per second would be stretching the system. From the [benchmarks done in 2017](https://dgraph.io/blog/post/benchmark-neo4j/), we achieved 46.7K txn per second. I do not understand why would bulk loader not work for your use case?
Here is the explanation for bulk loader.
Dgraph Bulk Loader serves a similar purpose to the Dgraph Live Loader, but can only be used to load data into a new cluster. It cannot be run on an existing Dgraph cluster.

**Comment by anurags92** [comment]
You mean you have an existing cluster in which you want to bulk commit the transactions?

**Comment by heshuguo** [comment]
> You mean you have an existing cluster in which you want to bulk commit the transactions?

yes, I am trying to use dgraph live to import rdf data

**Comment by anurags92** [comment]
I don't think live loader can handle that kind of load. :(

**Comment by parasssh** [comment]
Based on recent tests, Live loader can do upto 10K rdfs / sec on average. However, a lot will depend on the data set and the XIDs as well.

**Comment by heshuguo** [comment]
> I don't think live loader can handle that kind of load. :(

Any suggestion?

**Comment by anurags92** [comment]
I think the only way would be to use bulk loader.

**Comment by MichelDiz** [comment]
If you don't mind about ACID, you can use Ludicrous mode (With Liveloader) and get 100k/RDFs or more. I got 400k/RDFs on my Ryzen 2700X with NVMe. See https://discuss.dgraph.io/t/sharing-some-numbers-from-the-ludicrous-mode/6310

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8260). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
