### ISSUE TITLE
client.login_into_namespace

### ISSUE THREAD

**Issue by romeshshil** [dgraph-io/pydgraph#179]
login_into_namespace funciton is not working 
client.login_into_namespace("groot", "password", "1")

Getting a error  AttributeError: 'NoneType' object has no attribute 'txn'

**Comment by MaxxReis** [comment]
Hi @romeshshil I couldn't reproduce the same error.

login_into_namespace expects the namespace parameter to be an int.

this way is working for me.
client.login_into_namespace("groot", "password", 0).

**Comment by rarvikar** [comment]
Closing as this works as expected.
