### ISSUE TITLE
List pydgraph incompatabilities with v0.9

### ISSUE THREAD

**Issue by kochhar** [dgraph-io/pydgraph#18]
The dgraph website says:
>  Incomplete
>
> A lot of development has gone into the Go client and the Python client is not up to date with it. The Python client is not compatible with dgraph v0.9.0 and onwards. We are looking for help from contributors to bring it up to date. 

Is there a list of incompatibilities available? I'd be willing to contribute some patches to pydgraph.

**Comment by Levatius** [comment]
I would also be interested in finding out what needs to updated.

**Comment by jimanvlad** [comment]
Linking to: https://github.com/dgraph-io/dgraph/issues/1847
@pawanrawal Any ideas?

**Comment by pawanrawal** [comment]
The client needs to be refactored from scratch because the API has changed significantly. It should be very easy to do so though if one follows the [Go client](https://github.com/dgraph-io/dgraph/tree/master/client). All the code is less than 300 lines of code (txn.go and client.go).

We also have clients in JS and Java which you could follow.

**Comment by kochhar** [comment]
Seems like the API protobuf is defined here: https://github.com/dgraph-io/dgraph/blob/master/protos/api.proto

Thanks, this is very helpful.

**Comment by jimanvlad** [comment]
@kochhar: @Levatius and I are planning to allocate some resource to this next week. Would be great to see where you got so far and see if we can collab.

**Comment by kochhar** [comment]
I have a rough working client with new protobufs in a branch. It needs a proper set of tests. I will update the present tests with the new interface. 
https://github.com/kochhar/pydgraph/tree/kochhar/v0.9.4+

I still need to add async support but I'm not sure where to find the grpc docs for async interfaces. This is a good point to extend.

**Comment by jimanvlad** [comment]
Hi, we have our first working version here: https://github.com/jimanvlad/pydgraph
Will document and extend with async.

**Comment by pawanrawal** [comment]
Great work guys! If we can also add some integration tests that would be awesome. 

We have a bunch of them for the Go client at https://github.com/dgraph-io/dgraph/tree/master/contrib/integration though not all are important. `acctupsert`, `bank` and `testtxn` should be good.

**Comment by jimanvlad** [comment]
@pawanrawal Is there any document that explains transactions via grpc technically? We're trying to get our head around them and how to add them to the python module in an intuitive way.

**Comment by kochhar** [comment]
Hi Vlad, would you like to collaborate on this? I have implemented txns in
my fork, we could merge these together to save on duplication.

**Comment by jimanvlad** [comment]
@kochhar Sure, are you on Slack / any other way of collaborating?

**Comment by kochhar** [comment]
@jimanvlad sure, I've joined the pydgraph slack, will ping you there.

**Comment by kochhar** [comment]
I've opened a PR here: https://github.com/dgraph-io/pydgraph/pull/19
- acct upsert integration test is passing

To run, pip install pydgraph then:
    python tests/test_integration.py

**Comment by gpahal** [comment]
I have created a pull request for a revamped pydgraph with support for Dgraph v1
See: https://github.com/dgraph-io/pydgraph/pull/21

It would really help if someone could give it a try and report problems and bugs.

**Comment by gpahal** [comment]
Pushed to master.
