### ISSUE TITLE
Report clear and useful error when using non-cloud client against Dgraph Cloud

### ISSUE THREAD

**Issue by damonfeldman** [dgraph-io/pydgraph#211]
### Have you tried Pydgraph before this proposal? and did not find anything similar?

None

### What you wanted to do.

Get clear error when connecting incorrectly to a cloud endpoint.

For the below situation, the error could be prefixed with

```Unable to connect. If this is a Dgraph Cloud endpoint, please connect using ' pydgraph.DgraphClientStub.from_cloud' ```

### What you actually did.

Tried to connect to Dgraph Cloud via
```

client_stub = pydgraph.DgraphClientStub('[zzzzzzzzz.grpc.us-west-2.aws.cloud.dgraph.io:443](http://zzzzzzzz.grpc.us-west-2.aws.cloud.dgraph.io:443/)')
client = pydgraph.DgraphClient(client_stub)
client.login_into_namespace("abcdabcd", "xxxxxxx", 1)
```

### Why wasn't it great, with examples.

When trying to connect to gRPC from the cloud env - getting error message:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses; last error: INTERNAL: ipv4:xx.xx.xx.xx:443: Trying to connect an http1.x server"
debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: INTERNAL: ipv4:4xx.xx.xx.xx:443: Trying to connect an http1.x server {created_time:"2023-08-30T12:31:18.393056+10:00", grpc_status:14}"
```

### Additional information.

This is because the from_cloud() method with an api key is needed as in 
```

client_stub = pydgraph.DgraphClientStub.from_cloud("https://xxxxxxxx.eu-central-1.aws.cloud.dgraph.io/graphql", "<api-key>")
client = pydgraph.DgraphClient(client_stub) 
```

**Comment by rarvikar** [comment]
The incorrect function was used to create a 'stub' object for Cloud endpoints. The correct function to use is `DgraphClientStub.from_cloud(), which works as expected. 
Hence closing this issue.
