### ISSUE TITLE
[Request] Use More Flexible Dependency Versions for grpcio and protobuf

### ISSUE THREAD

**Issue by gautambhat** [dgraph-io/pydgraph#222]
## Issue Description

While integrating `pydgraph` into our project, we've encountered dependency conflicts due to the strict version pinning for `grpcio` and `protobuf` (grpcio==1.54.0 and protobuf==4.22.3). Other libraries in our project require newer versions of these dependencies, leading to incompatibility issues.

## Suggested Changes

To enhance compatibility and allow for more flexibility, we suggest adjusting the version pinning strategy in `pydgraph` to use the caret (^) operator, which would allow non-breaking updates:
- `grpcio >=1.54.0, < 2.0.0`
- `protobuf >=4.22.3, <5.0.0`

This modification will ensure that `pydgraph` can continue to receive important updates (including security and performance improvements) from these dependencies, without the risk of introducing breaking changes.

## Benefits

- **Broader Compatibility:** Using the caret operator allows `pydgraph` to be compatible with projects that rely on newer, backward-compatible versions of `grpcio` and `protobuf`.
- **Enhanced Security and Stability:** This change will enable users to benefit from the latest patches and minor updates that often include security patches and minor enhancements.

## Conclusion

We believe adopting this version strategy will solve the current conflicts we are experiencing and will also benefit the wider `pydgraph` community by reducing future compatibility issues. We appreciate the effort you put into maintaining this and thank you for considering this enhancement.

Best,
Gautam Bhat

**Comment by gautambhat** [comment]
@ryanfoxtyler wanted your thoughts on this...is there a reason you're pinned to exact versions?

**Comment by mangalaman93** [comment]
Hi @gautambhat, Thank you for creating the issue. Would you be open to create a PR to fix it? I can get on it in a couple of day if you can't. Thanks

**Comment by gautambhat** [comment]
@mangalaman93 I created https://github.com/dgraph-io/pydgraph/pull/233 - I will let you take a look and change anything that I may not have accounted for - thanks!

**Comment by josephsw** [comment]
This compatibility seems to have been broken in pydgraph 24.0.2 by #255 (where regenerating the protobuf sources with `grpc-tools` >= 1.66.0 changed the warning in api_pb2_grpc.py to a RuntimeError).

Our project is currently stuck on `grpcio` 1.65.5 due to Apache Beam not currently supporting `gprcio` >= 1.66.0 due to test issues since September 2024: https://github.com/grpc/grpc/issues/37710

I've published a PR to fix this by pinning `grpc-tools` to <1.66.0.
