### ISSUE TITLE
Query - get_all - Multiple Inputs

### ISSUE THREAD

**Issue by amandalmia14** [dgraph-io/pydgraph#26]
Hi,

As stated over here [link,](https://github.com/dgraph-io/pydgraph#run-a-query) it query for 'Alice' and it results for all the information for 'Alice'.

What if I have 'n' inputs  in order to get all information say 'Alice', 'Bob', etc.

What would be the query?
I tried with list or array but not working.

**Comment by MichelDiz** [comment]
Thread: https://discuss.dgraph.io/t/query-get-all-multiple-inputs/3037
