### ISSUE TITLE
Add preds field

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/pydgraph#34]
The preds field was added in Dgraph v1.0.8. It tracks the predicates mutated in a transaction and is handled by the client similar to the keys field by merging in the new list with the existing one per transaction.

Corresponding Go client change: https://github.com/dgraph-io/dgo/commit/ed3c52b47d0905d2ef0fbc0a636f1692a6368322

**Comment by martinmr** [comment]
Fixed by #41
