### ISSUE TITLE
Version pinning in requirements.txt

### ISSUE THREAD

**Issue by KevOrr** [dgraph-io/pydgraph#70]
Is there any reason that the `protobuf` dependency in requirements.txt is pinned to 3.6.1? This is very odd for libraries, since it will cause conflicts if other libraries require for e.g. `>=3.7`.

I noticed that the dependency for `grpcio` was recently changed so that its version isn't pinned anymore (#51). Is there some reason that `protobuf` stayed pinned?

Thanks

**Comment by danielmai** [comment]
I can't think of any good reasons to pin `protobuf`. We should unpin it like we did with `grpcio`.
