### ISSUE TITLE
python3 import error

### ISSUE THREAD

**Issue by manuel-delverme** [dgraph-io/pydgraph#9]
when i try to initialize it i get:

``` python
import pydgraph.client
pydgraph.client.DgraphClient("localhost", 8001)

```

`ImportError: No module named 'graphresponse_pb2'`

but if change the cwd like this:
!cd /usr/local/lib/python3.5/dist-packages/pydgraph

everything works

``` python
pydgraph.client.DgraphClient("localhost", 8001)
```

<pydgraph.client.DgraphClient at 0x7f5ecfb3b128>

**Comment by jimanvlad** [comment]
Hi,

Where do you change the CWD? I am getting the same error.

**Comment by gpahal** [comment]
Python 3 import should now work properly. For example, refer the README.
