### ISSUE TITLE
Why do you update Simple Example to use simplified type definitions in schema?

### ISSUE THREAD

**Issue by Li-Siyuan** [dgraph-io/pydgraph#96]
In my test the code in "pydgraph/examples/simple/simple.py" is not valid:
![234](https://user-images.githubusercontent.com/24380060/68592937-34468680-04cf-11ea-88c1-eed863f11bdf.png)
It doesn't run correctly until I change it back like this:
![123](https://user-images.githubusercontent.com/24380060/68592976-5213eb80-04cf-11ea-829f-6da357c14e2a.png)

does it have other use to update Simple Example to use simplified type definitions in schema?

**Comment by SoaringTiger** [comment]
I have the same issue.

**Comment by martinmr** [comment]
Sorry, there's a coming change in Dgraph that will simplify type definitions but has not been released yet. It looks like the documentation was updated before the new version of dgraph was released.

**Comment by martinmr** [comment]
I'll see if I can revert the changes and merge them back when the new version is ready.
